# arxivの学問領域の指定
subject: 'cat:ccss.* OR cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 3
        resnet: 3
        anomaly detection: 1
        shogi: 3
        reinforcement learning: 1
        image sensor: 1
        cutting force estimation: 2
        GAN: 1

# 通知の閾値
score_threshold: 0
